model_class_path: ped_pareto_mcts.gen_models.rnn.LSTMNextTokenLM
model_config:
  embed_dim: 128
  max_len: 100
  hidden_dim: 256
train_config:
  training_method: scheduled_sampling
  teacher_decay: 0.99 #valid if scheduled_sampling
  lr: 0.001
  lr_decay: 0.995
  