outdir: logs/hydros_04_06_26
use_selfies: True

gen_model:
  model_file: data/gen_models/hydros_minimal_transformer/hydros_minimal_transformer.pt
  vocab_file: data/gen_models/hydros_minimal_transformer/hydros_minimal_transformer.json

MCTS:
  class_path: ped_pareto_mcts.mcts.pareto_cycler.ParetoMCTSCycler
  max_gen_mols: 1000
  exploration_const: 1.5
  maxlen: 50
  
objective_functions:
  logP:
    class_path: ped_pareto_mcts.objectives.rdkit.logpObjective
    kwargs: {}
  QED:
    class_path: ped_pareto_mcts.objectives.rdkit.qedObjective
    kwargs: {}
  TPSA:
    class_path: ped_pareto_mcts.objectives.rdkit.tpsaObjective
    kwargs: {}
  MolWt:
    class_path: ped_pareto_mcts.objectives.rdkit.molwtObjective
    kwargs: {}
  VinaScore:
    class_path: ped_pareto_mcts.objectives.smina_score.VinaScore
    kwargs:
      receptor_file: data/receptors/cb7.sdf
  ped:
    class_path: ped_pareto_mcts.objectives.ped.PairwiseEmbeddingDistance
    kwargs:
      encoder_file: data/hydros_minimal/hydros_minimal_pretrained_encoder.pt
      smiles_to_graph_file: data/hydros_minimal/hydros_minimal_config.json
